### ISSUE TITLE
Implement OAuth2 Flow for signing in

### ISSUE THREAD

**Issue by alexanderson1993** [Thorium-Sim/thoriumsim.com#5]
There should be at least two flows supported:

- [OAuth for native apps](https://www.oauth.com/oauth2-servers/oauth-native-apps/) for when the user is signing in directly from the Thorium Nova app. This is doable because we can implement an app URL scheme and use that as the redirect URL for the app in question.
- [OAuth for devices](https://www.oauth.com/oauth2-servers/device-flow/) for when the user is signing in with a browser connected to a separate server. We can't use a regular browser or SPA flow because there is no way for us to know what the redirect URL should be, and dynamic redirect URLs are a security risk.

**Tasks for Native Apps**
- [ ] Implement a URL schema for the app
- [ ] Implement authorization API
- [ ] Implement auth page.
- [ ] Implement access token API.

**Tasks for Devices**
- [x] [Device Code Request](https://www.oauth.com/oauth2-servers/device-flow/authorization-request/)
- [x] Webpage to enter the device code
- [x] Client polling of authorization server
- [x] Rate limiting for the auth server
